# SPDX-License-Identifier: GPL-2.0

TEST_PROGS := reset_stress.sh reset_corner_cases.sh client_stress.sh cap_monkey.sh run_validation.sh
TEST_FILES := validate_consistency.py validate_concurrent.py README.md HOWTO.md

include ../../lib.mk
